{
  "$id": "https://TGenNorth.github.io/nasp.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Northern Arizona SNP Pipeline",
  "type": "object",
  "properties": {
    "reference": {
      "default": "reference.fasta",
      "description": "TODO",
      "type": "string"
    },
    "assemblies": {
      "default": "assemblies",
      "description": "TODO",
      "type": "string"
    },
    "pe_reads": {
      "default": "pe_reads",
      "description": "directory containing paired-end fastq files",
      "type": "string"
    },
    "se_reads": {
      "default": "se_reads",
      "description": "directory containing single-end fastq files",
      "type": "string"
    },
    "ubam": {
      "default": "ubam",
      "description": "directory containing unaligned sam/bam/cram files",
      "type": "string"
    },
    "minimum_coverage": {
      "default": 10,
      "description": "TODO",
      "minimum": 0,
      "type": "integer"
    },
    "minimum_proportion": {
      "default": 0.9,
      "description": "TODO",
      "maximum": 1,
      "minimum": 0,
      "type": "number"
    }
  }
}
