on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        # https://github.com/bioconda/bioconda-recipes/blob/3f5d499fd3c0bdf259710a228a8e49752b4c7996/README.md
        # The bioconda channel is a Conda channel providing bioinformatics related packages for Linux and Mac OS.
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          path: workflow
          persist-credentials: false
      - uses: actions/checkout@v2
        with:
          path: src
          persist-credentials: false
          ref: dev
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#add-a-system-path-add-path
      - name: install NASP
        working-directory: src/nasp
        run: |
          go env
          go install
          echo "::add-path::$(go env GOPATH)/bin"

        # CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
        # To initialize your shell, run
        #
        #     $ conda init <SHELL_NAME>
        #
        # Currently supported shells are:
        #   - bash
        #   - fish
        #   - tcsh
        #   - xonsh
        #   - zsh
        #   - powershell
        #
        # See 'conda init --help' for more information and options.
        #
        # IMPORTANT: You may need to close and restart your shell after running 'conda init'.
        #
        # ---------------------------------------------------------------------------------------------
        #
        # The default ~/.bashrc starts with an early return for non-interactive shells:
        #     case $- in
        #         *i*) ;;
        #           *) return;;
        #     esac
        #
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#using-a-specific-shell
        # bash --noprofile --norc -eo pipefail {0}
        #
        # --------------------------------------------------------------------------------------------
        #
        # # >>> conda initialize >>>
        # # !! Contents within this block are managed by 'conda init' !!
        # __conda_setup="$('/home/runner/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
        # if [ $? -eq 0 ]; then
        #     eval "$__conda_setup"
        # else
        #     if [ -f "/home/runner/miniconda3/etc/profile.d/conda.sh" ]; then
        #         . "/home/runner/miniconda3/etc/profile.d/conda.sh"
        #     else
        #         export PATH="/home/runner/miniconda3/bin:$PATH"
        #     fi
        # fi
        # unset __conda_setup
        # # <<< conda initialize <<<
        #
        # --------------------------------------------------------------------------------------------
      - name: install conda
        run: |
          PLATFORM=Linux
          [[ "$RUNNER_OS" == "macOS" ]] && PLATFORM="MacOSX"
          curl -LO https://repo.anaconda.com/miniconda/Miniconda3-latest-${PLATFORM}-x86_64.sh
          bash Miniconda3-latest-${PLATFORM}-x86_64.sh -b -u
          . "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda update -q -y -n base -c defaults conda
          conda --version
          conda config \
            --prepend channels defaults \
            --prepend channels bioconda \
            --prepend channels conda-forge
      - name: install snakemake
        run: |
          . "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda create -n snakemake -q -y -c conda-forge -c bioconda snakemake
      - name: snakemake testdata
        run: |
          . "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda activate snakemake
          snakemake --use-conda testdata
      - name: run snakemake
        run: |
          . "$HOME/miniconda3/etc/profile.d/conda.sh"
          conda activate snakemake
          snakemake --list-target-rules \
          | xargs snakemake --use-conda -j --
